### ISSUE TITLE
UMCloudDj failing on jenkins throwing sys.stdout.encoding as None instead of UTF-8

### ISSUE THREAD

**Issue by varunasingh** [UstadMobile/UMCloudDj-Code#9]
When unit tests are run under jenkins, it would throw an error message due to encoding not set. 

File "/mnt/jenkins/jobs/UMCloudDj-ustadmobile/workspace/uploadeXe/../exelearning-ustadmobile-work/exe/exe_do", line 176, in <module>
    parser = prepareParser()
  File "/mnt/jenkins/jobs/UMCloudDj-ustadmobile/workspace/uploadeXe/../exelearning-ustadmobile-work/exe/exe_do", line 69, in prepareParser
    help:\n%prog -h").encode(sys.stdout.encoding)
TypeError: encode() argument 1 must be string, not None
FTraceback (most recent call last):
  File "/mnt/jenkins/jobs/UMCloudDj-ustadmobile/workspace/uploadeXe/../exelearning-ustadmobile-work/exe/exe_do", line 176, in <module>
    parser = prepareParser()
  File "/mnt/jenkins/jobs/UMCloudDj-ustadmobile/workspace/uploadeXe/../exelearning-ustadmobile-work/exe/exe_do", line 69, in prepareParser
    help:\n%prog -h").encode(sys.stdout.encoding)
TypeError: encode() argument 1 must be string, not None

**Comment by varunasingh** [comment]
As per https://code.google.com/p/gitinspector/issues/detail?id=19 
this issue is solved when running: 

export PYTHONIOENCODING=utf-8; 

before running the jenkins build script.
